---
- name: Converge
  hosts: all
  remote_user: ansible
  debugger: on_failed
  roles:
    - role: ansible-role-hostname
      vars:
        hostname_fqdn: "test-{{ ansible_distribution | lower }}.example.com"
        hostname_hosts:
          192.168.1.222: test-foobar.com
