---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: hostnamecentos8
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/centos:8
    pre_build_image: true
  - name: hostnamedebian10
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/debian:10
    pre_build_image: true
  - name: hostnameubuntu2004
    image: registry.gitlab.com/dvonessen/docker-molecule-nonroot/ubuntu:20.04
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      interpreter_python: auto_silent
lint: |
  set -e
  yamllint -c .yamllint .
  flake8
  ansible-lint
